export const regions = [
  {
    id: 'macico_de_baturite',
    name: 'Maçico de Baturité',
    artigo: 'no',
    info: 'Maciço de Baturité <br>13 cidades<br>população: +390.000',
    cities: [
      'Acarapé',
      'Aracoiaba',
      'Aratuba',
      'Barreira',
      'Baturité',
      'Capistrano',
      'Guaramiranga',
      'Itapiúna',
      'Mulungu',
      'Ocara',
      'Pacoti',
      'Palmácia',
      'Redenção'
    ]
  },
  {
    id: 'litoral_oeste',
    name: 'Litoral Oeste',
    artigo: 'no',
    info: 'Litoral Oeste<br>12 cidades<br>população: +380.000',
    cities: [
      'Amontada',
      'Apuiarés',
      'General Sampaio',
      'Irauçuba',
      'Itapajé',
      'Itapipoca',
      'Miraíma',
      'Pentecoste',
      'Tejuçuoca',
      'Tururu',
      'Umirim',
      'Uruburetama'
    ]
  },
  {
    id: 'cariri',
    name: 'Cariri',
    artigo: 'no',
    info: 'Cariri<br>29 cidades<br>população: +1.000.000',
    cities: [
      'Abaiara',
      'Altaneira',
      'Antonina do Norte',
      'Araripe',
      'Assaré',
      'Aurora',
      'Barbalha',
      'Barro',
      'Brejo Santo',
      'Campos Sales',
      'Caririaçu',
      'Crato',
      'Farias Brito',
      'Granjeiro',
      'Jardim',
      'Jati',
      'Juazeiro do Norte',
      'Lavras da Mangabeira',
      'Mauriti',
      'Milagres',
      'Missão Velha',
      'Nova Olinda',
      'Penaforte',
      'Porteiras',
      'Potengi',
      'Salitre',
      'Santana do Cariri',
      'Tarrafas',
      'Várzea Alegre'
    ]
  },
  {
    id: 'centro_sul',
    name: 'Centro Sul',
    artigo: 'no',
    info: 'Centro Sul<br>13 cidades<br>+390.000',
    cities: [
      'Acopiara',
      'Baixio',
      'Cariús',
      'Catarina',
      'Cedro',
      'Icó',
      'Iguatu',
      'Ipaumirim',
      'Jucás',
      'Orós',
      'Quixelô',
      'Saboeiro',
      'Umari'
    ]
  },
  {
    id: 'sertao_central',
    name: 'Sertão Central',
    artigo: 'no',
    info: 'Sertão Central<br>13 cidades<br>população: +390.000',
    cities: [
      'Banabuiú',
      'Choró',
      'Deputado Irapuan Pinheiro',
      'Ibaretama',
      'Ibicuitinga',
      'Milhã',
      'Mombaça',
      'Pedra Branca',
      'Piquet Carneiro',
      'Quixadá',
      'Quixeramobim',
      'Senador Pompeu',
      'Solonópole'
    ]
  },
  {
    id: 'serra_da_ibiapaba',
    name: 'Serra da Ibiapaba',
    artigo: 'na',
    info: 'Serra da Ibiapaba<br>9 cidades<br>população: +350.00',
    cities: [
      'Carnaubal',
      'Croatá',
      'Guaraciaba do Norte',
      'Ibiapina',
      'Ipu',
      'São Benedito',
      'Tianguá',
      'Ubajara',
      'Viçosa do Ceará'
    ]
  },
  {
    id: 'sertao_de_sobral',
    name: 'Sertão de Sobral',
    artigo: 'no',
    info: 'Sertão de Sobral<br>18 cidades<br>população: +490.00',
    cities: [
      'Alcântaras',
      'Cariré',
      'Coreaú',
      'Forquilha',
      'Frecheirinha',
      'Graça',
      'Groaíras',
      'Massapê',
      'Meruoca',
      'Moraújo',
      'Mucambo',
      'Pacujá',
      'Pires Ferreira',
      'Reriutaba',
      'Santana do Acaraú',
      'Senador Sá',
      'Sobral',
      'Varjota'
    ]
  },
  {
    id: 'litoral_norte',
    name: 'Litoral Norte',
    artigo: 'no',
    info: 'Litoral Norte<br>13 cidades<br>população: +390.000',
    cities: [
      'Acaraú',
      'Barroquinha',
      'Bela Cruz',
      'Camocim',
      'Chaval',
      'Cruz',
      'Granja',
      'Itarema',
      'Jijoca de Jericoacoara',
      'Marco',
      'Martinópole',
      'Morrinhos',
      'Uruoca'
    ]
  },
  {
    id: 'sertao_dos_inhamuns',
    name: 'Sertão dos Inhamuns',
    artigo: 'no',
    info: 'Sertão dos Inhamuns<br>5 cidades<br>população: +130.000',
    cities: ['Aiuaba', 'Arneiroz', 'Parambu', 'Quiterianópolis', 'Tauá']
  },
  {
    id: 'sertao_dos_crateus',
    name: 'Sertão dos Crateús',
    artigo: 'no',
    info: 'Sertão dos Crateús<br>13 cidades<br>população: +340.000',
    cities: [
      'Ararendá',
      'Catunda',
      'Crateús',
      'Hidrolândia',
      'Independência',
      'Ipaporanga',
      'Ipueiras',
      'Monsenhor Tabosa',
      'Nova Russas',
      'Novo Oriente',
      'Poranga',
      'Santa Quitéria',
      'Tamboril'
    ]
  },
  {
    id: 'sertao_de_caninde',
    name: 'Sertão de Canindé',
    artigo: 'no',
    info: 'Sertão de Canindé<br>6 cidades<br>população +200.000',
    cities: [
      'Boa Viagem',
      'Canindé',
      'Caridade',
      'Itatira',
      'Madalena',
      'Paramoti'
    ]
  },
  {
    id: 'vale_do_jaguaribe',
    name: 'Vale do Jaguaribe',
    artigo: 'no',
    info: 'Vale do Jaguaribe<br>15 cidades<br>população +390.000',
    cities: [
      'Alto Santo',
      'Ererê',
      'Iracema',
      'Jaguaretama',
      'Jaguaribara',
      'Jaguaribe',
      'Limoeiro do Norte',
      'Morada Nova',
      'Palhano',
      'Pereiro',
      'Potiretama',
      'Quixeré',
      'Russas',
      'São João do Jaguaribe',
      'Tabuleiro do Norte'
    ]
  },
  {
    id: 'litoral_leste',
    name: 'Litoral Leste',
    artigo: 'no',
    info: 'Litoral Leste<br>6 cidades<br>população +200.000',
    cities: [
      'Aracati',
      'Beberibe',
      'Fortim',
      'Icapuí',
      'Itaiçaba',
      'Jaguaruana'
    ]
  },
  {
    id: 'grande_fortaleza',
    name: 'Grande Fortaleza',
    artigo: 'na',
    info: 'Grande Fortaleza</br>19 cidade</br> +4.000.000',
    cities: [
      'Aquiraz',
      'Cascavel',
      'Caucaia',
      'Chorozinho',
      'Eusébio',
      'Fortaleza',
      'Guaiúba',
      'Horizonte',
      'Itaitinga',
      'Maracanaú',
      'Maranguape',
      'Pacajus',
      'Pacatuba',
      'Paracuru',
      'Paraipaba',
      'Pindoretama',
      'São Gonçalo do Amarante',
      'São Luis do Curu',
      'Trairi'
    ]
  }
]
